global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "node_exporter"
    static_configs:
      - targets:
          ["isucon-server1:9100", "isucon-server2:9100", "isucon-server3:9100"]

  - job_name: "process_exporter"
    static_configs:
      - targets:
          ["isucon-server1:9256", "isucon-server2:9256", "isucon-server3:9256"]
